name: docker-build

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_KEY }}
      - name: Build and push
        run: |
          docker build -t ghcr.io/iotdb-lab/iotdb-cli:latest .
          docker push ghcr.io/iotdb-lab/iotdb-cli:latest