name: test-install-mac

on:
  pull_request:
      branches: [ main ]

jobs:
  test-install-script:
    name: Test install script for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test install script
        run: |
          curl -s https://raw.githubusercontent.com/francis-du/iotdb-cli/main/install.sh | bash -ex
          curl -s https://raw.githubusercontent.com/francis-du/iotdb-cli/main/install.sh | bash -ex